Update limitAmountSwap function
gyrostable/balancer-sor-public-fork pull request #2
Opened 2022-10-31 13:12 UTC by joshguha

2022-10-31 18:49 UTC, sschuldenzucker requested changes
Looking good except see comments.

Another kind request: Could you add a comment explaining that the two parameters in `Gyro2PoolPairData` are automatically adjusted so that one assumes the in-asset is x and the out-asset is y? I was a bit confused at first b/c I thought these were read directly from the contracts then was looking for a case distinction that wasn't there.

2022-10-31 18:49 UTC, sschuldenzucker commented on src/pools/gyro2Pool/gyro2Pool.ts
> +                poolPairData.sqrtBeta.sub(poolPairData.sqrtAlpha)
This looks wrong. Assume `!tokenInIsToken0` like in the writeup. Then `poolPairData.sqrtAlpha == 1/gyro2Pool.sqrtBeta` and `poolPairData.sqrtBeta == 1/gyro2Pool.sqrtAlpha`. Then  `maxAmountInAssetInPool == invariant * (1/gyro2Pool.sqrtAlpha - 1/gyro2Pool.sqrtBeta)`. But in the writeup we want `maxAmountInAssetInPool  == y+ = invariant * (poolPairData.sqrtBeta - gyro2Pool.sqrtAlpha)`.
I think you want the formula for x+ from the writeup?

2022-10-31 18:49 UTC, sschuldenzucker commented on src/pools/gyro2Pool/gyro2Pool.ts
> +                    18
Is it intended to change the number of decimals from `poolPairData.decimalsIn` to 18 here? You didn't do this for the else branch.

2022-10-31 18:49 UTC, sschuldenzucker commented on src/pools/gyro3Pool/gyro3Pool.ts
> +                    18
same as above: Is it intended to change the number of decimals to 18 here?

2022-11-01 12:35 UTC, joshguha commented on src/pools/gyro2Pool/gyro2Pool.ts
> +                    18
Hi @sschuldenzucker, the formatFixed function takes a BigNumber and decimals value and returns a string. Since the scaling factor of the result in the if branch is 10^18, there's an '18' there. However, in the else branch, there is no 'normalization' of the balance, thus the relevant scaling factor is decimalsOut

2022-11-01 12:35 UTC, joshguha commented on src/pools/gyro3Pool/gyro3Pool.ts
> +                    18
Same here

2022-11-01 12:35 UTC, joshguha commented on src/pools/gyro2Pool/gyro2Pool.ts
> +                poolPairData.sqrtBeta.sub(poolPairData.sqrtAlpha)
I think you're right - there is some error here. Your writeup assumes that x is in the out-asset, but does it also assume that x is token 0, as the original paper describes? 

For the calculation of maximum values permissible in the pool of either asset, I don't think it's relevant which asset is the 'in' asset. 

If `tokenInIsToken0` then I think the above line 181 should be replaced by 

`divDown(ONE, poolPairData.sqrtAlpha).sub(divDown(ONE, poolPairData.sqrtBeta))` (i.e. the formula for x+)

However, if `!tokenIsInToken0`, because `poolPairData.sqrtBeta` = 1 / sqrtAlpha and `poolPairData.sqrtAlpha` = 1 / sqrtBeta. We don't actually need to make any changes with the line 181 replacement above.

2022-11-01 12:57 UTC, merged